# Generated by Django 3.2.11 on 2022-06-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_step_number_step_step_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
